language: node_js
node_js:
  - 10
cache:
  directories:
    - node_modules
script:
  - npm run build
  - npm run build:storybook
deploy:
  provider: pages
  skip_cleanup: true
  keep_history: true
  github_token: $GITHUB_TOKEN
  local_dir: build
on:
  branch: master
